name: SkyResoursePack
version: '${version}'
main: me.skyscx.skyresoursepack.SkyResoursePack
api-version: '1.20'
author: Skyscx_
website: https://github.com/Skyscx
commands:
  resourcepack:
    aliases:
      - rp
    description: Установка и загрузка пакета ресурсов.
    usage: /rp help