name: SkyResourcePack
version: '${version}'
main: me.skyscx.skyresourcepack.SkyResourcePack
api-version: '1.20'
author: Skyscx_
website: https://github.com/Skyscx
commands:
  resourcepack:
    aliases:
      - rp
    description: Установка и загрузка пакета ресурсов.
    usage: /rp help
  test:
    description: Test
    usage: /test for test